"""
This YAML file defines the Variable Groups and Values
that are used in the Azure DevOps Pipeline for connecting 
the DevOps pipeline to the Azure Machine Learning Workspace 
and Azure Resource Group using Service Connection via Azure Agents. 

DevOps -> Library -> Variable Groups

"""


pr: none
trigger: none

variables:
- group: mlops-wsh-vg

stages:
- stage: 'Dev'
  displayName: 'Dev'
  jobs:
  - job: "Provision_Dev"
    displayName: "Provision Dev resources"
    pool:
      vmImage: 'ubuntu-latest'
    timeoutInMinutes: 0
    steps:
    - task: AzureResourceGroupDeployment@2
      inputs:
        azureSubscription: '$(AZURE_RM_SVC_CONNECTION)'
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(RESOURCE_GROUP)'
        location: $(LOCATION)
        templateLocation: 'Linked artifact'
        csmFile: '$(Build.SourcesDirectory)/environment_setup/cloud-environment.json'
        overrideParameters: '-baseName $(BASE_NAME) -location $(LOCATION) -workspace $(WORKSPACE_NAME)'
        deploymentMode: 'Incremental'
      displayName: 'Deploy OH resources to Azure'
